variables:
  Project name: basic-react-template
  Description: Project description
features:
  - basic:
      description: Basic react template
  - with-store:
      description: Adds store
conflicts:
  - with-storybook
excludes:
  - /.github
