variables:
  Project name: basic-react-template
  Description: Project description
features:
  - basic:
      description: Basic react template
  - with-storybook:
      description: Storybook integration in react basic template
conflicts:
  - with-store
excludes:
  - /.github
